const constants = {
    ADD_USER: 'ADD_USER',
    FETCH_USER_INFO: 'FETCH_USER_INFO',
    FETCH_USERS: 'FETCUSERS',
    FETCH_USERS_FAILURE: 'FETCH_USERS_FAILURE',
    FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
    FETCH_USERS_REQUEST: 'FETCH_USERS_REQUEST',
    REMOVE_USER: 'REMOVE_USER',
    REMOVE_USER_SUCCESS: 'REMOVE_USER_SUCCESS',
    REMOVE_USER_FAILURE: 'REMOVE_USER_FAILURE',
};

export default constants;
